### ISSUE TITLE
A DDLm version of imgCIF is needed.

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/imgCIF#1]
imgCIF is written in DDL2, which is mostly due to its origins as an extension to mmCIF (also written in DDL2). At the category and dataname level nothing (or very little?) in imgCIF is mmCIF-specific and so imgCIF datanames are also suitable for describing single-crystal or powder raw data images.  The dictionaries underlying these other techniques are now written in DDLm. DDLm provides a machine-actionable way of describing the relationship between imgCIF categories and (DDLm) core CIF categories (the import mechanism), and machine-readable algorithms via dREL. Thus a DDLm version of imgCIF would provide the wider crystallographic community with the datanames upon which a machine-actionable description of data reduction for all crystallographic experiments can be built. A further advantage of DDLm is that recent accretions to imgCIF that are not relevant to the wider community can be presented separately in extension dictionaries with no loss of functionality.

However, the PDB are unlikely to move away from DDL2 in the medium term, and this _may_ imply that imgCIF is also tied to DDL2. We are faced with a few options:

1. Maintain a "master" DDL2 version of imgCIF which is auto-translated to DDLm
2. Maintain a "master" DDLm version of imgCIF which is auto-translated to DDL2
3. Switch entirely to DDLm if there is no significant tooling which parses the current imgCIF 

Note that *no* data names would have different meanings in a DDLm imgCIF, and therefore the primary consequence of a DDLm imgCIF is for tools that read the DDL2 dictionary file.  Any scenario involving translation of DDLm to DDL2 would need to pass muster with these tools, so a list of tools and use-cases would be helpful.  Any software that does not read in the imgCIF dictionary at compilation or runtime should be completely unaffected by any of the changes under discussion.

**Comment by jamesrhester** [comment]
The explicit link with mmCIF in imgCIF appears to be only through `_diffrn.id` and categories which include children of this data name:

1. `_diffrn_detector`
2. `_diffrn_measurement`
3. `_diffrn_refln`

The PDB mmCIF website indicates that `_diffrn_refln` is not used in any current PDB entries. `_diffrn_refln` also extends the category key of the PDBX/mmCIF `_diffrn_refln` category (It is not clear how this is specified and adapted to when ingesting data files into the PDB.)

**Comment by jdwestbrook** [comment]
You are quite correct that PDB has no plans to move away from DDL2.  We are in the process of  significantly extending our coverage of data collection content at this time which will pull content 
from the  imgCIF dictionary.  

It is not clear to me what is driving this discussion.   If there is a need to handle dictionary import
and composition, then  the semantics for this exist in DDL2.  If there is a need to translate the DDL2 
content to an alternative metadata representation, then we can probably leverage some existing tools for this purpose.  I prototyped something like this several years for one of the COMCIFs workshops.

**Comment by yayahjb** [comment]
Dear Colleagues,

  I agree with the need for a DDLm version of the imgCIF dictionary, and
that auto-translation from the DDL2 imgCIF dictionary is a useful starting
point, inasmuch as that will illuminate any needed extensions to DDLm and
dREL to support imgCIF.  John's suggestion of building on his earlier
prototype efforts seems sensible.

  To allow this work to be shared and viewed by the community, I would
suggest posting the relevant support software repository URLs to this list,
and moving towards having masters or forks of those repositories on github
in the COMCIFS organization.  It is the software that will clarify the
semantics of dealing with this complex data.

  Regards,
      Herbert

**Comment by jamesrhester** [comment]
@jdwestbrook yes this is being driven by a need for an alternative metadata representation (DDLm).

So it sounds like there is no objection to producing a DDLm imgCIF, possibly using @jdwestbrook 's tools.

**Comment by jamesrhester** [comment]
A version of imgCIF in DDLm produced by Syd Hall before the Montreal meeting has just been added to the imgCIF repository. There is no implication that this is canonical or accepted, I am simply cleaning out the cif_core repository to contain only the core DDLm dictionaries so the other dictionaries are moving into their own repositories. That said, I have been using a version of this dictionary for several years when testing various DDLm tools and it is a good starting point for thinking about DDL2/DDLm issues.

**Comment by jamesrhester** [comment]
An automatically-generated and round-trippable DDLm version is now in the repository.
