### ISSUE TITLE
core CIF import should specify dupl behaviour

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/imgCIF#12]
The imgCIF dictionary imports the core CIF dictionary, but several categories are duplicated in core CIF. The desired behaviour in these cases should be specified - in this case, the imgCIF categories take priority so 'ignore' is correct.

**Comment by jamesrhester** [comment]
Fixed by #13

**Comment by vaitkus** [comment]
Great, thanks. However, the import statement should actually have the `dupl` field instead of `if_dupl`.

**Comment by jamesrhester** [comment]
Fixed in #14
