### ISSUE TITLE
_array_intensities.array_id is not a component of the key of _array_intensities

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/imgCIF#6]
For the same reason as #5 , `binary_id` is sufficient to uniquely identify the image under discussion. `array_id` provides no further information and can be either dropped (as the array structure can be accessed through `binary_id`) or demoted to a simple data name.

**Comment by yayahjb** [comment]
This is incorrect.  This is intentionally a composite key.  See my response
to issue 5.
